name: Retouch
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - scikit-learn
  - tqdm
  - pillow
  - joblib
  - threadpoolctl
  - openssl
  - ca-certificates
  - tzdata
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - filelock==3.19.1
      - fsspec==2025.10.0
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.2.1
      - pillow==11.3.0
      - sympy==1.14.0
      - torch==2.8.0+cu128
      - torchaudio==2.8.0+cu128
      - torchvision==0.23.0+cu128
      - typing-extensions==4.15.0
